#include "ReadDataByIdentifier.cpp"
#include "WriteDataByIdentifier.cpp"
#include "SecurityAccess.cpp"
#include "DiagnosticSessionControl.cpp"
#include "ControlDTCSettings.cpp"
#include "CommunicationControl.cpp"
#include "RequestDownload.cpp"
#include "TransferData.cpp"
#include "RequestTransferExit.cpp"
#include "ECUReset.cpp"

#include "DID.cpp"
