# This is a basic workflow to help you get started with Actions

name: Build & Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Installing Qt
        run: sudo apt-get install qt5-default libqt5serialbus5-dev libqt5serialport5-dev
      - name: Creating build environment
        run: mkdir ${{github.workspace}}/build &&
             cd ${{github.workspace}}/build &&
             cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        run: make
      - name: Test
        run: make test
